### PR TITLE
Consul vault auth

### PR DESCRIPTION
**Pull request by stuart-c**
This requires #177 to be merged first.

Add ability to get Consul token from Vault dynamic secret backend

### CODE REVIEW

**Comment by hairyhenderson** [comment]
@stuart-c this looks good so far, but will need to be rebased

**Comment by stuart-c** [comment]
@hairyhenderson I think this one should be ready too...

**Comment by hairyhenderson** [comment]
Thanks @stuart-c 😁

**Comment by stuart-c** [comment]
Thanks!

Would it be possible to cut a release with the recent changes?

**Comment by hairyhenderson** [comment]
@stuart-c I'll be releasing v2.0.0 soon - I want to get #194 merged first.

**Comment by hairyhenderson** [comment]
@stuart-c FYI https://github.com/hairyhenderson/gomplate/releases/tag/v2.0.0 is out now 🎉

**Pull request merged**
