### PR TITLE
Bump go4.org/unsafe/assume-no-moving-gc for Go 1.21 support

### PR DESCRIPTION
**Pull request by stefanb**
Upgrades indirect dependancy `go4.org/unsafe/assume-no-moving-gc` for compatibility with upcoming Go 1.21: https://github.com/go4org/unsafe-assume-no-moving-gc/commit/e7c30c78aeb2bf1ab602f2e789b86db8d9942388

Full upstream diff: https://github.com/go4org/unsafe-assume-no-moving-gc/compare/c31fa085b70e...e7c30c78aeb2

It is required via (now archived) module `inet.af/netaddr` that is used in some Deprecated functions of the public API.

Problem noticed in https://github.com/Homebrew/homebrew-core/pull/134468
Log: https://github.com/Homebrew/homebrew-core/actions/runs/5618619997/job/15224884480?pr=134468#step:3:9232

>==> /opt/homebrew/Cellar/gomplate/3.11.5/bin/gomplate --version
  panic: Something in this program imports go4.org/unsafe/assume-no-moving-gc to declare that it assumes a non-moving garbage collector, but your version of go4.org/unsafe/assume-no-moving-gc hasn't been updated to assert that it's safe against the go1.21rc3 runtime. If you want to risk it, run with environment variable ASSUME_NO_MOVING_GC_UNSAFE_RISK_IT_WITH="go1.21rc3" set. Notably, if go1.21rc3 adds a moving garbage collector, this program is unsafe to use.

I was able to reproduce the error locally with Go 1.21rc3, but afrer bumping the go4.org/unsafe/assume-no-moving-gc the error went away.

### CODE REVIEW

**Review by hairyhenderson — APPROVED** [review]

**Comment by hairyhenderson** [comment]
Thanks @stefanb, I appreciate this!

**Comment by hairyhenderson** [comment]
Hmm... if you're installing `github.com/hairyhenderson/gomplate/v4` you shouldn't be seeing this (because of this PR)... I would expect this to happen with gomplate v3 though - can you double-check your `go install` command?

**Comment by mihaitodor** [comment]
@hairyhenderson I am installing v4, but the issue is that `@latest` picks up the latest tagged release, namely `v4.0.0-pre-0`, which doesn't contain the fix. Try running the following:

```shell
> go install github.com/hairyhenderson/gomplate/v4/cmd/gomplate@latest
go: downloading github.com/hairyhenderson/gomplate/v4 v4.0.0-pre-0
...
some more output...
...
```

**Comment by hairyhenderson** [comment]
🤦‍♂️ I totally forgot `v4.0.0-pre-0` existed... sorry about that. I'll tag a `-1` soon!

**Comment by hairyhenderson** [comment]
Done: https://github.com/hairyhenderson/gomplate/releases/tag/v4.0.0-pre-1 - sorry for the confusion!

**Comment by mihaitodor** [comment]
Thank you very much! ❤️

**Comment by erharb** [comment]
> Hmm... if you're installing `github.com/hairyhenderson/gomplate/v4` you shouldn't be seeing this (because of this PR)... I would expect this to happen with gomplate v3 though - can you double-check your `go install` command?

@hairyhenderson I am currently using gomplate v3 and can confirm we just hit this after updating to go 1.21.1

```bash
go: downloading github.com/hairyhenderson/gomplate/v3 v3.11.5
...
panic: Something in this program imports go4.org/unsafe/assume-no-moving-gc to declare that it assumes a non-moving garbage collector, but your version of go4.org/unsafe/assume-no-moving-gc hasn't been updated to assert that it's safe against the go1.21 runtime. If you want to risk it, run with environment variable ASSUME_NO_MOVING_GC_UNSAFE_RISK_IT_WITH="go1.21" set. Notably, if go1.21 adds a moving garbage collector, this program is unsafe to use.
```

**Pull request merged**
