### PR TITLE
New function proposal: `files.Walk`

### PR DESCRIPTION
**Pull request by christopher-avila**

### CODE REVIEW

**Comment by hairyhenderson** [comment]
Hi @christopher-avila, thank you for this contribution!

Can you please describe what you're aiming for with `file.FindFiles`? You should be able to accomplish the same effect with a template similar to this:

```console
$ gomplate -i '{{ range file.ReadDir "." }}{{ if not (file.IsDir .) }}{{ . }} IS A FILE{{"\n"}}{{ end }}{{ end -}}'
Gopkg.toml IS A FILE
LICENSE IS A FILE
CHANGELOG.md IS A FILE
...
```

As for `strings.TrimPrefix` - that seems like a reasonable addition, but I'd rather it be adapted to work better in a pipeline. This means that I should be able to use it in a template like `{{ print "Hello, World!" | strings.TrimPrefix "Hello, " }}`. To do this the signature needs its arguments swapped so the input string is last. See the `strings.Trim` function -  https://github.com/hairyhenderson/gomplate/pull/281/files#diff-3011984e758821c934ac913b336f80d3L82 - as an example.

Ideally I like to also have tests and documentation added for any new functions. If you're not comfortable with these I can add them in after.

Thanks!

**Comment by robermorales** [comment]
Any update on this?

**Comment by christopher-avila** [comment]
I'm modifying the `files.FindFiles` function, naming it `files.Walk`. It looks like a better name for the function (is actually a wrapper over `filepath.Walk`). I'll commit this changes on this PR and will open another one for `strings.TrimPreffix`.

Thanks for your time!

**Comment by christopher-avila** [comment]
From: https://ci.appveyor.com/project/hairyhenderson/gomplate/build/637

```
--- FAIL: TestFileWalk (0.00s)
	Error Trace:	file_test.go:47
	Error:      	Not equal: 
	            	expected: []string{"/tmp", "/tmp/bar", "/tmp/bar/baz"}
	            	actual  : []string{"/tmp", "\\tmp\\bar", "\\tmp\\bar\\baz"}
```

Any idea of this? =/

**Comment by hairyhenderson** [comment]
Thanks @christopher-avila!

I'm thinking the issue has to do with Windows path separators. If you instead use `filepath.Join` to create the expected paths you should _in theory_ be OK. I'm not sure why the first element is `/tmp` though... Perhaps an odd quirk in how afero's `Walk` is implemented.

**Comment by christopher-avila** [comment]
I think it is solved. Take a look! 

Thanks for your time! :)

**Comment by hairyhenderson** [comment]
Thanks again for the contribution, @christopher-avila!

**Comment by christopher-avila** [comment]
Thanks to you for your time!

**Pull request merged**
