### PR TITLE
Added ppc64le support

### PR DESCRIPTION
**Pull request by mayurwaghmode**
This PR will add ppc64le support to the gomplate image.

### CODE REVIEW

**Comment by mayurwaghmode** [comment]
@hairyhenderson can u please review the PR?

**Comment by hairyhenderson** [comment]
Thanks for the PR @mayurwaghmode. I will consider this. Can you clarify what the use-case is for ppc64le?

**Comment by mayurwaghmode** [comment]
Thank you @hairyhenderson for considering the PR. We need the ppc64le supported release binary of gomplate tool for building the https://github.com/dexidp/dex package.

**Comment by mayurwaghmode** [comment]
@hairyhenderson can u please take a look at this PR?

**Comment by hairyhenderson** [comment]
@mayurwaghmode It's on my list - I haven't forgotten. Please continue to be patient and I will get to it when I have time.

**Comment by hairyhenderson** [comment]
I've found time to test this out, and it looks like it works - thanks @mayurwaghmode

**Comment by hairyhenderson** [comment]
CI failure's unrelated - merging anyway...

**Comment by mayurwaghmode** [comment]
Thanks, @hairyhenderson :)
Can we expect gomplate binaries for ppc64le architecture as part of the releases?

**Comment by hairyhenderson** [comment]
Yes, the next release will contain these. If you need a build in the meantime you can use the `latest` or `alpine` tags of the Docker image: https://hub.docker.com/r/hairyhenderson/gomplate/tags

**Comment by mayurwaghmode** [comment]
@hairyhenderson when we are planning for the next release of gomplate?

**Comment by mayurwaghmode** [comment]
@hairyhenderson is there any update regarding the next release of gomplate?

**Pull request merged**
