### PR TITLE
add support for default-datasource

### PR DESCRIPTION
**Pull request by moshloop**

### CODE REVIEW

**Comment by hairyhenderson** [comment]
@moshloop Thanks for the contribution! Can you please explain your use-case, and why you think this change is necessary?

It seems like this may be also achievable by implementing #404, which I've started working on.

**Comment by moshloop** [comment]
My use case is templating out a bunch of files using variables provided at runtime. e.g. Apache load balancing members etc..

The template shouldn't care where the data is coming from, just that there is data to merge in. 

#404 does get a little of the way there, but would still need to include the arbitrary data source name for every invocation

i.e. we want these to be equivalent:

```
$ gomplate -d config=some:///config/source -i '{{ (ds "config").value }}'
$ gomplate -d config=some:///config/source -i '{{ .value }} --default-datasource config'
```

**Comment by hairyhenderson** [comment]
One way this can be accomplished right now without any code changes is to use nested external templates:

```console
$ echo '{{ .value }}' > in.t
$ echo 'value: hello world' > config.yml
$ gomplate --template t=in.t --datasource config=config.yml --in '{{ template "t" (ds "config") }}'
hello world
```

The input string would remain the same, but the external template (`--template`/`-t`) would change.

**Comment by hairyhenderson** [comment]
@moshloop I think #424 supersedes this.

**Comment by moshloop** [comment]
@hairyhenderson thanks - #424 works as well

**Pull request closed without merging**
