### PR TITLE
Fix assignment to app.Action by removing error return

### PR DESCRIPTION
**Pull request by mdeheij**

### CODE REVIEW

**Comment by hairyhenderson** [comment]
Hi @mdeheij, thanks for the PR! Is there a specific issue that this fixes?

The `Action` field is an [`ActionFunc`](https://godoc.org/github.com/urfave/cli#ActionFunc), whose signature has an `error` returned:

```go
type ActionFunc func(*Context) error
```

Also see the doc for the `Action` field:

```go
// The action to execute when no subcommands are specified
// Expects a `cli.ActionFunc` but will accept the *deprecated* signature of `func(*cli.Context) {}`
// *Note*: support for the deprecated `Action` signature will be removed in a future version
Action interface{}
```

Perhaps you simply need to update your version of `github.com/codegangsta/cli`:

```console
$ go get -v -u github.com/codegangsta/cli
```

**Comment by hairyhenderson** [comment]
(also, thanks for the reminder - I've been meaning to update the dependency to `github.com/urfave/cli`)

**Comment by mdeheij** [comment]
I guess I forgot to update something somewhere. Seems to work now, thanks!

**Comment by hairyhenderson** [comment]
Ok, no worries! Thanks for using gomplate 😄

**Pull request closed without merging**
