### PR TITLE
Upgrade k8s client-go

### LINKED ISSUE #1061: Update k8s.io/client-go to a valid version
The current import of `k8s.io/client-go v11.0.0+incompatible` causes any project inheriting from this to loose their correct `k8s.io/client-go` import. Could you pick a version from K8s v1.17 upwards (`v0.x.y`) and use that library version (e.g. `k8s.io/client-go v0.18.15` for K8s v1.18).

If you have a dependency forcing you to `k8s.io/client-go v11.0.0+incompatible` please could you use the following pattern to fix projects consuming this project.

```go
// Pin kubernetes dependencies to 1.18.15
replace (
	k8s.io/api => k8s.io/api v0.18.15
	k8s.io/apimachinery => k8s.io/apimachinery v0.18.15
	k8s.io/client-go => k8s.io/client-go v0.18.15
)

require (
	k8s.io/client-go v11.0.0+incompatible
)
```

### PR DESCRIPTION
**Pull request by stevehipwell**
This PR upgrades `k8s.io/client-go` to version  `v0.17.17`, which is part of the official v0 group of releases. This release should make it easier to include gomplate as  a package as it will no longer include `k8s.io/client-go v11.0.0+incompatible` which is semantically a greater version than the newer versions in the v0 group.

Fixes #1061

### CODE REVIEW

**Comment by hairyhenderson** [comment]
Ah. Apparently CI doesn't work so well for PRs in forks anymore 🤦‍♂️ Let's see if I can fix it...

**Comment by stevehipwell** [comment]
@hairyhenderson it looks like the PR is failing due to issue https://github.com/actions/labeler/issues/12.

**Comment by hairyhenderson** [comment]
@stevehipwell the `label` check isn't required, but the other checks aren't even starting... 😞

**Comment by stevehipwell** [comment]
@hairyhenderson it looks like the build is expecting credentials? This is a trivial change so feel free to replicate it on a repo branch rather than a fork if that's easier.

**Comment by hairyhenderson** [comment]
Oh, there's an ongoing DockerHub issue, that's why the CircleCI build is failing: https://status.docker.com/pages/533c6539221ae15e3f000031

**Comment by stevehipwell** [comment]
I hadn't seen that, thanks.

**Comment by hairyhenderson** [comment]
This was duplicated in #1063 so I'll close this - sorry about that! I need to fix the CI tests that don't work for forks...

**Pull request closed without merging**
